import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import {
  createBrowserModeBookmarklet,
  extractPlayerResponseFromScripts,
  normalizeCaptionTracks,
  parseCaptionPayload,
  selectPreferredTrack,
} from "../src/browser-mode/bookmarklet.js";
import { validateBrowserModePayload } from "../src/browser-mode/receiverPayload.js";
import { createTranscriptFile, formatRawTranscript } from "../src/browser-mode/transcriptFiles.js";
import { EXTRACTION_SOURCES } from "../src/lib/extractionSources.js";
import { createAiFailureState, getFriendlyAiFailureMessage } from "../src/lib/aiUi.js";

const playerResponse = {
  videoDetails: {
    videoId: "M7lc1UVf-VE",
    title: "YouTube API demo",
    author: "Google for Developers",
  },
  captions: {
    playerCaptionsTracklistRenderer: {
      captionTracks: [
        {
          baseUrl: "https://www.youtube.com/api/timedtext?lang=es",
          languageCode: "es",
          name: { simpleText: "Spanish" },
        },
        {
          baseUrl: "https://www.youtube.com/api/timedtext?lang=en&kind=asr",
          languageCode: "en",
          kind: "asr",
          name: { simpleText: "English auto-generated" },
        },
        {
          baseUrl: "https://www.youtube.com/api/timedtext?lang=en",
          languageCode: "en",
          name: { simpleText: "English" },
        },
      ],
    },
  },
};

test("bookmarklet finds caption tracks and prefers manual English", () => {
  const script = `ytInitialPlayerResponse = ${JSON.stringify(playerResponse)};`;
  const extracted = extractPlayerResponseFromScripts([script], "M7lc1UVf-VE");
  const selected = selectPreferredTrack(normalizeCaptionTracks(extracted));

  assert.equal(selected.languageCode, "en");
  assert.equal(selected.isAutoGenerated, false);
  assert.equal(selected.name, "English");
});

test("bookmarklet parser supports JSON3, legacy XML, and srv3 XML", () => {
  const json = parseCaptionPayload(JSON.stringify({
    events: [{ tStartMs: 1000, dDurationMs: 1500, segs: [{ utf8: "JSON caption" }] }],
  }));
  const legacyXml = parseCaptionPayload(
    '<transcript><text start="2" dur="1">XML &amp; caption</text></transcript>',
  );
  const srv3 = parseCaptionPayload(
    '<timedtext><body><p t="3000" d="2000"><s>srv3 caption</s></p></body></timedtext>',
  );

  assert.deepEqual(json, [{ start: 1, duration: 1.5, text: "JSON caption" }]);
  assert.deepEqual(legacyXml, [{ start: 2, duration: 1, text: "XML & caption" }]);
  assert.deepEqual(srv3, [{ start: 3, duration: 2, text: "srv3 caption" }]);
});

test("receiver accepts only shaped payloads from a YouTube origin", () => {
  const payload = {
    version: 1,
    video: {
      videoId: "M7lc1UVf-VE",
      title: "YouTube API demo",
      channel: "Google for Developers",
      url: "https://www.youtube.com/watch?v=M7lc1UVf-VE",
    },
    track: { name: "English", languageCode: "en", isAutoGenerated: false },
    segments: [{ start: 1, duration: 2, text: "Receiver caption" }],
    importedAt: 1234,
  };

  assert.equal(validateBrowserModePayload(payload, "https://www.youtube.com").ok, true);
  assert.equal(validateBrowserModePayload(payload, "https://attacker.example").ok, false);
  assert.equal(validateBrowserModePayload({ ...payload, segments: [] }, "https://www.youtube.com").ok, false);
  assert.equal(validateBrowserModePayload({ videoUrl: payload.video.url }, "https://www.youtube.com").ok, false);
});

test("Browser Mode bookmarklet contains no backend transcript extraction route", () => {
  const bookmarklet = createBrowserModeBookmarklet(
    "https://www.yt2trascript.in/browser-mode/receiver",
  );

  assert.match(bookmarklet, /^javascript:/);
  assert.match(bookmarklet, /www\.yt2trascript\.in\/browser-mode\/receiver/);
  assert.match(bookmarklet, /segments/);
  assert.match(bookmarklet, /text:\s*formatRawTranscript\(segments\)/);
  assert.doesNotMatch(bookmarklet, /onrender\.com|localhost:10000|\/api\/transcript|NEXT_PUBLIC_BACKEND_URL/);
  assert.doesNotThrow(() => new Function(bookmarklet.slice("javascript:".length)));
});

test("raw transcript TXT and SRT files are produced without AI", () => {
  const payload = {
    video: { videoId: "M7lc1UVf-VE", title: "Demo video" },
    segments: [{ start: 1, duration: 2, text: "Local raw caption" }],
  };

  assert.equal(formatRawTranscript(payload.segments), "[00:01] Local raw caption");
  assert.deepEqual(createTranscriptFile(payload, "txt"), {
    filename: "Demo video.txt",
    content: "[00:01] Local raw caption",
    mimeType: "text/plain",
  });
  assert.match(createTranscriptFile(payload, "srt").content, /00:00:01,000 --> 00:00:03,000/);
});

test("source indicators expose Browser, Server, and Extension ownership", () => {
  assert.equal(EXTRACTION_SOURCES.browser.backendYouTubeFetch, false);
  assert.equal(EXTRACTION_SOURCES.browser.youtubeFetch, "User browser");
  assert.equal(EXTRACTION_SOURCES.server.backendYouTubeFetch, true);
  assert.equal(EXTRACTION_SOURCES.server.youtubeFetch, "Render backend");
  assert.equal(EXTRACTION_SOURCES.extension.backendYouTubeFetch, false);
  assert.equal(EXTRACTION_SOURCES.extension.youtubeFetch, "User browser/extension");
});

for (const action of ["clean", "summary", "notes"]) {
  test(`AI ${action} failure restores raw transcript and keeps downloads usable`, () => {
    const rawText = "[00:01] Raw transcript remains ready";
    const failure = createAiFailureState({
      action,
      code: action === "clean" ? "AI_UNDER_DEVELOPMENT" : "AI_UNAVAILABLE",
      rawText,
    });
    const payload = {
      video: { videoId: "M7lc1UVf-VE", title: "Failure-safe transcript" },
      segments: [{ start: 1, duration: 2, text: "Raw transcript remains ready" }],
    };

    assert.deepEqual(failure.activeOutput, { kind: "raw", text: rawText });
    assert.match(failure.message, /Raw transcript is safe and ready/);
    assert.equal(createTranscriptFile(payload, "txt").content, rawText);
    assert.match(createTranscriptFile(payload, "srt").content, /Raw transcript remains ready/);
  });
}

test("backend offline and under-development errors use product-safe copy", () => {
  assert.equal(
    getFriendlyAiFailureMessage("summary", "AI_UNAVAILABLE"),
    "Summary is temporarily unavailable. Raw transcript is safe and ready.",
  );
  assert.equal(
    getFriendlyAiFailureMessage("clean", "AI_UNDER_DEVELOPMENT"),
    "Clean transcript is under development right now. Raw transcript is safe and ready.",
  );
});

test("Browser Mode source does not import backend providers or youtube-transcript", async () => {
  const projectRoot = path.resolve(import.meta.dirname, "..");
  const browserModeFiles = await Promise.all([
    "src/browser-mode/bookmarklet.js",
    "src/browser-mode/receiverPayload.js",
    "src/browser-mode/transcriptFiles.js",
    "src/app/components/BrowserModeSetup.js",
  ].map((file) => readFile(path.join(projectRoot, file), "utf8")));
  const source = browserModeFiles.join("\n");

  assert.doesNotMatch(source, /youtubeTranscriptProvider|from\s+["']youtube-transcript["']|\/api\/transcript/);
  assert.doesNotMatch(source, /yt-transcript-server\/lib/);
});

test("homepage presents Browser Mode first and Server Mode as an advanced fallback", async () => {
  const projectRoot = path.resolve(import.meta.dirname, "..");
  const browserSetup = await readFile(
    path.join(projectRoot, "src/app/components/BrowserModeSetup.js"),
    "utf8",
  );
  const homePage = await readFile(path.join(projectRoot, "src/app/page.js"), "utf8");

  assert.match(browserSetup, /Browser Mode = User browser fetches YouTube/);
  assert.match(browserSetup, /Drag .Get Transcript. to your bookmarks bar/);
  assert.match(browserSetup, /Open YouTube video/);
  assert.match(browserSetup, /Click the bookmarklet/);
  assert.match(browserSetup, /Transcript opens here/);
  assert.match(homePage, /<details[^>]*>/);
  assert.match(homePage, /Advanced fallback · Server Mode/);
  assert.match(homePage, /Server Mode = Render backend fetches YouTube/);
  assert.match(homePage, /Try Server Fallback/);
  assert.match(homePage, /This uses our server to contact YouTube and may fail if the server is blocked/);
  assert.match(homePage, /Server fallback failed\. Try Browser Mode — it uses your browser instead of our server\./);
});

test("Browser Mode development log exposes ownership counts but not transcript content", async () => {
  const projectRoot = path.resolve(import.meta.dirname, "..");
  const receiverSource = await readFile(
    path.join(projectRoot, "src/app/browser-mode/receiver/page.js"),
    "utf8",
  );

  assert.match(receiverSource, /BROWSER_MODE_TRANSCRIPT_RECEIVED/);
  assert.match(receiverSource, /youtubeFetchByBackend:\s*false/);
  assert.match(receiverSource, /textLength:/);
  assert.match(receiverSource, /segments:/);
  assert.doesNotMatch(receiverSource, /console\.info\([^)]*activeOutput\.text/s);
});
