export type TranscriptSegment = {
  start: number;
  duration?: number;
  text: string;
};

export type CaptionTrack = {
  baseUrl: string;
  name: string;
  languageCode: string;
  isAutoGenerated: boolean;
  kind?: string;
};

export type VideoInfo = {
  videoId: string;
  title: string;
  channel: string;
  url: string;
};

export type RawCaptionTrack = {
  baseUrl?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
  languageCode?: string;
  kind?: string;
};

export type PlayerResponse = {
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    isPrivate?: boolean;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: RawCaptionTrack[];
    };
  };
  playabilityStatus?: {
    status?: string;
    reason?: string;
  };
};

export type TranscriptResult = {
  video: VideoInfo;
  segments: TranscriptSegment[];
  text: string;
  track: CaptionTrack;
  fetchedAt: number;
};

export type TranscriptErrorCode =
  | "UNSUPPORTED_PAGE"
  | "NO_VIDEO_ID"
  | "NO_PLAYER_DATA"
  | "NO_TRANSCRIPT"
  | "CAPTIONS_DISABLED"
  | "PRIVATE_VIDEO"
  | "NETWORK_ERROR"
  | "EXTRACTION_FAILED";

export type TranscriptError = {
  code: TranscriptErrorCode;
  message: string;
};

export type TranscriptResponse =
  | { ok: true; data: TranscriptResult }
  | { ok: false; error: TranscriptError };

export type GetTranscriptMessage = {
  type: "GET_TRANSCRIPT";
};

export type VideoChangedMessage = {
  type: "VIDEO_CHANGED";
  videoId: string | null;
};

export type ReadPlayerResponseMessage = {
  type: "READ_PLAYER_RESPONSE";
  expectedVideoId: string;
};

export type FetchCaptionTrackMessage = {
  type: "FETCH_CAPTION_TRACK";
  url: string;
};

export type AiAction = "clean" | "summary" | "notes";

export type RunAiActionMessage = {
  type: "RUN_AI_ACTION";
  action: AiAction;
  videoId: string;
  transcript: string;
};

export type ContentMessage = GetTranscriptMessage;
export type BackgroundMessage =
  | ReadPlayerResponseMessage
  | FetchCaptionTrackMessage
  | RunAiActionMessage;

export type PlayerResponseMessageResult = {
  ok: true;
  playerResponse: PlayerResponse | null;
};

export type CaptionTrackMessageResult =
  | { ok: true; rawText: string }
  | { ok: false; error: TranscriptError };

export type AiActionMessageResult =
  | { ok: true; text: string }
  | { ok: false; error: { code: string; message: string } };
