export function decodeHtmlEntities(value) {
  const namedEntities = {
    amp: "&",
    apos: "'",
    gt: ">",
    lt: "<",
    nbsp: " ",
    quot: '"',
  };

  return value.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (entity, token) => {
    if (token.startsWith("#x")) return String.fromCodePoint(Number.parseInt(token.slice(2), 16));
    if (token.startsWith("#")) return String.fromCodePoint(Number.parseInt(token.slice(1), 10));
    return namedEntities[token.toLowerCase()] ?? entity;
  });
}

function normalizeText(value) {
  return value.replace(/\s+/g, " ").trim();
}

function readAttribute(attributes, name) {
  const match = attributes.match(new RegExp(`\\b${name}=["']([^"']+)["']`, "i"));
  return match?.[1] ?? null;
}

function stripXmlTags(value) {
  return value.replace(/<[^>]+>/g, "");
}

function parseXmlNodes(rawXml, tagName, startAttribute, durationAttribute, divisor) {
  const nodePattern = new RegExp(`<${tagName}\\b([^>]*)>([\\s\\S]*?)<\\/${tagName}>`, "gi");
  const segments = [];

  for (const match of rawXml.matchAll(nodePattern)) {
    const attributes = match[1] ?? "";
    const startValue = readAttribute(attributes, startAttribute);
    const durationValue = readAttribute(attributes, durationAttribute);
    const start = startValue === null ? Number.NaN : Number(startValue) / divisor;
    const text = normalizeText(decodeHtmlEntities(stripXmlTags(match[2] ?? "")));

    if (!Number.isFinite(start) || !text) continue;

    const segment = { start, text };
    if (durationValue !== null) {
      const duration = Number(durationValue) / divisor;
      if (Number.isFinite(duration)) segment.duration = duration;
    }
    segments.push(segment);
  }

  return segments;
}

export function parseCaptionPayload(rawText) {
  const trimmed = rawText.trim();
  if (!trimmed) return [];

  if (trimmed.startsWith("{")) {
    const payload = JSON.parse(trimmed);
    return (payload.events ?? [])
      .map((event) => {
        const text = normalizeText((event.segs ?? []).map((segment) => segment.utf8 ?? "").join(""));
        if (!text || typeof event.tStartMs !== "number") return null;

        const segment = { start: event.tStartMs / 1000, text };
        if (typeof event.dDurationMs === "number") segment.duration = event.dDurationMs / 1000;
        return segment;
      })
      .filter(Boolean);
  }

  const legacySegments = parseXmlNodes(trimmed, "text", "start", "dur", 1);
  return legacySegments.length > 0
    ? legacySegments
    : parseXmlNodes(trimmed, "p", "t", "d", 1000);
}

function readTrackName(track) {
  if (track.name?.simpleText) return track.name.simpleText;
  return (track.name?.runs ?? []).map((run) => run.text ?? "").join("").trim()
    || track.languageCode
    || "Caption track";
}

export function normalizeCaptionTracks(playerResponse) {
  const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return tracks
    .map((track) => {
      if (!track.baseUrl || !track.languageCode) return null;
      return {
        baseUrl: track.baseUrl,
        name: readTrackName(track),
        languageCode: track.languageCode,
        isAutoGenerated: track.kind === "asr",
        ...(track.kind ? { kind: track.kind } : {}),
      };
    })
    .filter(Boolean);
}

export function selectPreferredTrack(tracks) {
  const manualEnglish = tracks.find(
    (track) => track.languageCode.startsWith("en") && !track.isAutoGenerated,
  );
  const anyManual = tracks.find((track) => !track.isAutoGenerated);
  const english = tracks.find((track) => track.languageCode.startsWith("en"));
  return manualEnglish || anyManual || english || tracks[0] || null;
}

function extractBalancedJsonObject(source, startIndex) {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = startIndex; index < source.length; index += 1) {
    const character = source[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === '"') inString = false;
      continue;
    }

    if (character === '"') inString = true;
    else if (character === "{") depth += 1;
    else if (character === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(startIndex, index + 1);
    }
  }

  return null;
}

export function extractPlayerResponseFromScripts(scriptTexts, expectedVideoId) {
  const markers = ["ytInitialPlayerResponse =", '"ytInitialPlayerResponse":'];

  for (const scriptText of scriptTexts) {
    for (const marker of markers) {
      let searchFrom = 0;
      while (searchFrom < scriptText.length) {
        const markerIndex = scriptText.indexOf(marker, searchFrom);
        if (markerIndex === -1) break;

        const jsonStart = scriptText.indexOf("{", markerIndex + marker.length);
        if (jsonStart === -1) break;
        const json = extractBalancedJsonObject(scriptText, jsonStart);
        searchFrom = jsonStart + 1;
        if (!json) continue;

        try {
          const candidate = JSON.parse(json);
          if (candidate?.videoDetails?.videoId === expectedVideoId) return candidate;
        } catch {
          // Continue because YouTube may include unrelated or changing inline data.
        }
      }
    }
  }

  return null;
}

function formatTimestamp(totalSeconds) {
  const seconds = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const remainingSeconds = seconds % 60;
  const pad = (value) => String(value).padStart(2, "0");
  return hours > 0
    ? `${pad(hours)}:${pad(minutes)}:${pad(remainingSeconds)}`
    : `${pad(minutes)}:${pad(remainingSeconds)}`;
}

export function formatRawTranscript(segments) {
  return segments.map((segment) => `[${formatTimestamp(segment.start)}] ${segment.text}`).join("\n");
}

async function runBrowserModeBookmarklet(receiverUrl) {
  const currentUrl = new URL(location.href);
  const allowedHosts = new Set(["youtube.com", "www.youtube.com", "m.youtube.com"]);
  const videoId = currentUrl.pathname === "/watch"
    ? currentUrl.searchParams.get("v")
    : (currentUrl.pathname.startsWith("/shorts/") ? currentUrl.pathname.split("/")[2] : null);

  if (!allowedHosts.has(currentUrl.hostname) || !/^[a-zA-Z0-9_-]{11}$/.test(videoId || "")) {
    alert("Open a YouTube video with available captions, then click Get Transcript again.");
    return;
  }

  const receiverOrigin = new URL(receiverUrl).origin;
  const receiverWindow = window.open(receiverUrl, "yt2t-browser-mode");
  if (!receiverWindow) {
    alert("Your browser blocked the transcript receiver window. Allow popups for YouTube and try again.");
    return;
  }

  let outboundMessage = null;
  let finished = false;
  const deliver = () => {
    if (!finished && outboundMessage) receiverWindow.postMessage(outboundMessage, receiverOrigin);
  };
  const cleanup = () => {
    finished = true;
    clearInterval(deliveryTimer);
    window.removeEventListener("message", handleReceiverMessage);
  };
  const handleReceiverMessage = (event) => {
    if (event.source !== receiverWindow || event.origin !== receiverOrigin) return;
    if (event.data?.type === "YT2T_RECEIVER_READY") deliver();
    if (event.data?.type === "YT2T_IMPORT_ACK") cleanup();
  };
  window.addEventListener("message", handleReceiverMessage);
  const deliveryTimer = setInterval(deliver, 500);
  setTimeout(cleanup, 30000);

  try {
    const player = document.getElementById("movie_player");
    let playerResponse = window.ytInitialPlayerResponse
      || (typeof player?.getPlayerResponse === "function" ? player.getPlayerResponse() : null);

    if (!playerResponse || playerResponse?.videoDetails?.videoId !== videoId) {
      playerResponse = extractPlayerResponseFromScripts(
        Array.from(document.scripts, (script) => script.textContent || ""),
        videoId,
      );
    }

    if (!playerResponse) throw new Error("YouTube player data is not available yet. Refresh the video and try again.");

    const tracks = normalizeCaptionTracks(playerResponse);
    const selectedTrack = selectPreferredTrack(tracks);
    if (!selectedTrack) throw new Error("This video does not have an available caption track.");

    const captionUrl = new URL(selectedTrack.baseUrl);
    captionUrl.searchParams.set("fmt", "json3");
    const response = await fetch(captionUrl.toString(), { credentials: "include" });
    if (!response.ok) throw new Error(`YouTube returned HTTP ${response.status} for captions.`);

    const segments = parseCaptionPayload(await response.text());
    if (segments.length === 0) throw new Error("Caption data was found, but no transcript text could be parsed.");

    const channel = playerResponse.videoDetails?.author
      || document.querySelector("ytd-channel-name a, #owner-name a")?.textContent?.trim()
      || "Unknown channel";
    const title = playerResponse.videoDetails?.title
      || document.title.replace(/\s*-\s*YouTube\s*$/, "").trim()
      || "YouTube video";

    outboundMessage = {
      type: "YT2T_TRANSCRIPT_IMPORT",
      payload: {
        version: 1,
        video: { videoId, title, channel, url: location.href },
        track: {
          name: selectedTrack.name,
          languageCode: selectedTrack.languageCode,
          isAutoGenerated: selectedTrack.isAutoGenerated,
        },
        segments,
        text: formatRawTranscript(segments),
        importedAt: Date.now(),
      },
    };
  } catch (error) {
    outboundMessage = {
      type: "YT2T_IMPORT_ERROR",
      error: error instanceof Error ? error.message : "Transcript extraction failed.",
    };
  }

  deliver();
  receiverWindow.focus();
}

export function createBrowserModeBookmarklet(receiverUrl) {
  const helpers = [
    decodeHtmlEntities,
    normalizeText,
    readAttribute,
    stripXmlTags,
    parseXmlNodes,
    parseCaptionPayload,
    readTrackName,
    normalizeCaptionTracks,
    selectPreferredTrack,
    extractBalancedJsonObject,
    extractPlayerResponseFromScripts,
    formatTimestamp,
    formatRawTranscript,
  ].map((helper) => helper.toString()).join("\n");

  return `javascript:(()=>{${helpers}\n(${runBrowserModeBookmarklet.toString()})(${JSON.stringify(receiverUrl)});})()`;
}
