const MAX_SEGMENTS = 100000;
const MAX_TRANSCRIPT_CHARACTERS = 10 * 1024 * 1024;

export function isAllowedYouTubeOrigin(origin) {
  try {
    const url = new URL(origin);
    return url.protocol === "https:"
      && ["youtube.com", "www.youtube.com", "m.youtube.com"].includes(url.hostname);
  } catch {
    return false;
  }
}

export function validateBrowserModePayload(payload, origin) {
  if (!isAllowedYouTubeOrigin(origin)) return { ok: false, error: "Untrusted transcript source." };
  if (!payload || payload.version !== 1) return { ok: false, error: "Unsupported transcript payload." };

  const { video, segments, track } = payload;
  if (!video || !/^[a-zA-Z0-9_-]{11}$/.test(video.videoId || "")) {
    return { ok: false, error: "Invalid YouTube video information." };
  }

  try {
    const videoUrl = new URL(video.url);
    if (!["youtube.com", "www.youtube.com", "m.youtube.com"].includes(videoUrl.hostname)) {
      return { ok: false, error: "Invalid YouTube video URL." };
    }
  } catch {
    return { ok: false, error: "Invalid YouTube video URL." };
  }

  if (typeof video.title !== "string" || typeof video.channel !== "string") {
    return { ok: false, error: "Incomplete video information." };
  }
  if (!Array.isArray(segments) || segments.length === 0 || segments.length > MAX_SEGMENTS) {
    return { ok: false, error: "Invalid transcript segments." };
  }

  let totalCharacters = 0;
  const normalizedSegments = [];
  for (const segment of segments) {
    if (!segment
      || !Number.isFinite(segment.start)
      || segment.start < 0
      || typeof segment.text !== "string"
      || !segment.text.trim()) {
      return { ok: false, error: "Invalid transcript segment." };
    }

    const text = segment.text.trim();
    totalCharacters += text.length;
    if (totalCharacters > MAX_TRANSCRIPT_CHARACTERS) {
      return { ok: false, error: "Transcript payload is too large." };
    }

    normalizedSegments.push({
      start: segment.start,
      text,
      ...(Number.isFinite(segment.duration) && segment.duration >= 0
        ? { duration: segment.duration }
        : {}),
    });
  }

  return {
    ok: true,
    data: {
      version: 1,
      video: {
        videoId: video.videoId,
        title: video.title.slice(0, 500),
        channel: video.channel.slice(0, 300),
        url: video.url,
      },
      track: {
        name: typeof track?.name === "string" ? track.name.slice(0, 200) : "Captions",
        languageCode: typeof track?.languageCode === "string" ? track.languageCode.slice(0, 30) : "unknown",
        isAutoGenerated: Boolean(track?.isAutoGenerated),
      },
      segments: normalizedSegments,
      importedAt: Number.isFinite(payload.importedAt) ? payload.importedAt : Date.now(),
    },
  };
}
